import 'dart:convert';

/// Service for exporting interview data in various formats
class DataExportService {
  /// Export sessions to CSV format
  String exportToCSV(List<dynamic> sessions) {
    final buffer = StringBuffer();

    // CSV Header
    buffer.writeln('Session ID,Position,Company,Level,Question Type,Score,Date');

    // CSV Rows
    for (final session in sessions) {
      buffer.writeln([
        session.id,
        '"${session.position}"',
        '"${session.company}"',
        session.level,
        session.questionType ?? 'Mixed',
        session.totalScore?.toInt() ?? 'N/A',
        session.createdAt?.toIso8601String() ?? '',
      ].join(','));
    }

    return buffer.toString();
  }

  /// Export sessions to JSON format
  String exportToJSON(List<dynamic> sessions) {
    final data = sessions.map((session) => {
          'id': session.id,
          'position': session.position,
          'company': session.company,
          'level': session.level,
          'questionType': session.questionType,
          'score': session.totalScore,
          'questionCount': session.questionCount,
          'createdAt': session.createdAt?.toIso8601String(),
        }).toList();

    return const JsonEncoder.withIndent('  ').convert({
      'exportDate': DateTime.now().toIso8601String(),
      'totalSessions': sessions.length,
      'sessions': data,
    });
  }

  /// Generate a text summary report
  String generateSummaryReport(List<dynamic> sessions) {
    if (sessions.isEmpty) return 'No sessions to report.';

    final scoredSessions = sessions.where((s) => s.totalScore != null).toList();
    final avgScore = scoredSessions.isEmpty
        ? 0
        : scoredSessions.map((s) => s.totalScore!).reduce((a, b) => a + b) /
            scoredSessions.length;

    final buffer = StringBuffer();
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('    InterviewAce Progress Report    ');
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('');
    buffer.writeln('📊 Overview');
    buffer.writeln('   Total Sessions: ${sessions.length}');
    buffer.writeln('   Average Score: ${avgScore.toInt()}%');
    buffer.writeln('   Total Questions: ${sessions.fold<int>(0, (int s, dynamic e) => s + (e.questionCount as int))}');
    buffer.writeln('');
    buffer.writeln('📈 Recent Sessions');
    for (final s in sessions.take(5)) {
      buffer.writeln('   • ${s.position} at ${s.company} — ${s.totalScore?.toInt() ?? "N/A"}%');
    }
    buffer.writeln('');
    buffer.writeln('Generated by InterviewAce');

    return buffer.toString();
  }
}
