import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:interview_ace/core/constants/app_colors.dart';

/// PDF-style report generator (outputs formatted text report)
/// For full PDF, consider adding the 'pdf' package
class ReportGeneratorService {
  /// Generate a comprehensive interview report
  String generateFullReport({
    required String position,
    required String company,
    required String level,
    required double score,
    required int questionCount,
    required String? overallFeedback,
    required String? strengths,
    required String? weaknesses,
    required List<Map<String, dynamic>> questions,
    required DateTime date,
  }) {
    final buf = StringBuffer();

    buf.writeln('╔══════════════════════════════════════════════════╗');
    buf.writeln('║          INTERVIEWACE ASSESSMENT REPORT          ║');
    buf.writeln('╚══════════════════════════════════════════════════╝');
    buf.writeln('');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('📋 SESSION DETAILS');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('  Position:    $position');
    buf.writeln('  Company:     $company');
    buf.writeln('  Level:       $level');
    buf.writeln('  Date:        ${date.day}/${date.month}/${date.year}');
    buf.writeln('  Questions:   $questionCount');
    buf.writeln('');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('📊 OVERALL SCORE');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('');
    buf.writeln('  ┌─────────────────────────────────────────┐');
    buf.writeln('  │                                         │');
    buf.writeln('  │          ${_scoreBar(score)}            │');
    buf.writeln('  │                                         │');
    buf.writeln('  │            ${score.toInt()}% — ${_gradeLabel(score)}             │');
    buf.writeln('  │                                         │');
    buf.writeln('  └─────────────────────────────────────────┘');
    buf.writeln('');

    if (overallFeedback != null) {
      buf.writeln('  💬 Feedback: $overallFeedback');
      buf.writeln('');
    }

    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('💪 STRENGTHS');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    if (strengths != null && strengths.isNotEmpty) {
      for (final s in strengths.split(',')) {
        buf.writeln('  ✅ ${s.trim()}');
      }
    } else {
      buf.writeln('  No strengths identified.');
    }
    buf.writeln('');

    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('📈 AREAS FOR IMPROVEMENT');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    if (weaknesses != null && weaknesses.isNotEmpty) {
      for (final w in weaknesses.split(',')) {
        buf.writeln('  ⚠️  ${w.trim()}');
      }
    } else {
      buf.writeln('  No areas identified.');
    }
    buf.writeln('');

    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('📝 QUESTION-BY-QUESTION ANALYSIS');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('');

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      buf.writeln('  Q${i + 1}: ${q['question'] ?? 'N/A'}');
      buf.writeln('  Answer: ${q['answer'] ?? 'Skipped'}');
      buf.writeln('  Score: ${q['score'] ?? 'N/A'}/100');
      if (q['feedback'] != null) buf.writeln('  Feedback: ${q['feedback']}');
      buf.writeln('  ─────────────────────────────────────');
      buf.writeln('');
    }

    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln('🎯 RECOMMENDATIONS');
    buf.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buf.writeln(_generateRecommendations(score));
    buf.writeln('');
    buf.writeln('═══════════════════════════════════════════════════');
    buf.writeln('  Generated by InterviewAce — AI Interview Coach');
    buf.writeln('  ${DateTime.now().toIso8601String().substring(0, 19)}');
    buf.writeln('═══════════════════════════════════════════════════');

    return buf.toString();
  }

  String _scoreBar(double score) {
    final filled = (score / 5).round();
    final empty = 20 - filled;
    return '[${'█' * filled}${'░' * empty}]';
  }

  String _gradeLabel(double score) {
    if (score >= 90) return 'Outstanding 🏆';
    if (score >= 80) return 'Excellent 🌟';
    if (score >= 70) return 'Good 👍';
    if (score >= 60) return 'Fair 📈';
    if (score >= 50) return 'Needs Work 💪';
    return 'Keep Practicing 🔄';
  }

  String _generateRecommendations(double score) {
    if (score >= 90) {
      return '  1. You\'re performing at an expert level!\n'
          '  2. Focus on leadership and mentoring skills\n'
          '  3. Practice explaining complex concepts simply\n'
          '  4. Consider preparing for senior/lead positions';
    }
    if (score >= 70) {
      return '  1. Strong foundation — refine your STAR stories\n'
          '  2. Practice quantifying your achievements\n'
          '  3. Work on structuring longer responses\n'
          '  4. Research company-specific scenarios';
    }
    return '  1. Practice daily to build confidence\n'
        '  2. Study the STAR method thoroughly\n'
        '  3. Prepare 5-7 stories covering key competencies\n'
        '  4. Record yourself and review your delivery\n'
        '  5. Focus on one weakness area per week';
  }
}
